language: java
dist: bionic
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
install: true
script:
- mvn clean verify
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
