dist: bionic

language: java 
jdk:
  - oraclejdk11
#  - openjdk10
  - openjdk11

#-----start GUI testing stuff
services:
  - xvfb
#-----end GUI testin stuff
cache:
  directories:
  - "$HOME/.m2"
install: true
script:
  - mvn clean verify -e
